version: '3.9'

services:
  server:
    container_name: "request-emulator"
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/request_emulator/app
    command: bash -c "cd ./request_emulator && sh ./scripts/start_app.sh"
