version: '3.9'

services:
  db-test:
    image: postgres:14.5
    container_name: postgres_test
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
    ports:
      - ${TEST_DB_PORT}:${TEST_DB_PORT}
    command: -p ${TEST_DB_PORT}
  app-test:
    container_name: api-test
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db-test
    command: bash -c "PYTHONPATH=/request_emulator/backend pytest"
