version: '3.9'

services:
  server:
    container_name: "request-emulator"
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["uvicorn", "request_emulator.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
