version: '3.9'

services:
  db:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    volumes:
      - ./backend:/request_emulator/backend
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: