"""updated relationships

Revision ID: 8d21bd5e458e
Revises: 321a28dfa3ac
Create Date: 2023-04-11 00:10:35.465040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d21bd5e458e'
down_revision = '321a28dfa3ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
